version: '3'

vars:
  BINARY_NAME: goman
  BUILD_DIR: build
  INSTALL_PATH: /usr/local/bin
  AWS_REGION: ap-south-1

tasks:
  # Default task
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Main build tasks
  build:
    desc: Build all binaries
    deps: [build:ui, build:lambda]
    cmds:
      - echo "✅ All binaries built successfully"

  build:ui:
    desc: Build the UI binary
    cmds:
      - echo "🔨 Building UI..."
      - go build -v -o {{.BINARY_NAME}} ./cmd/goman
    sources:
      - cmd/goman/**/*.go
      - pkg/**/*.go
    generates:
      - "{{.BINARY_NAME}}"

  build:lambda:
    desc: Build Lambda controller
    cmds:
      - echo "🔨 Building Lambda controller..."
      - mkdir -p {{.BUILD_DIR}}
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags aws -o {{.BUILD_DIR}}/bootstrap ./lambda/controller
      - cd {{.BUILD_DIR}} && zip -q lambda-aws-controller.zip bootstrap
      - echo "✅ Lambda package created at {{.BUILD_DIR}}/lambda-aws-controller.zip"
    sources:
      - lambda/controller/**/*.go
      - pkg/**/*.go
    generates:
      - "{{.BUILD_DIR}}/lambda-aws-controller.zip"

  # Run tasks
  run:
    desc: Run the UI
    deps: [build:ui]
    cmds:
      - ./{{.BINARY_NAME}}

  dev:
    desc: Run in development mode with auto-reload
    cmds:
      - |
        if command -v air &> /dev/null; then
          air
        else
          echo "❌ Air not installed. Install with:"
          echo "  go install github.com/cosmtrek/air@latest"
          exit 1
        fi

  # Installation tasks
  install:
    desc: Install goman to system path
    deps: [build:ui]
    cmds:
      - echo "📦 Installing {{.BINARY_NAME}} to {{.INSTALL_PATH}}..."
      - sudo cp {{.BINARY_NAME}} {{.INSTALL_PATH}}/
      - sudo chmod +x {{.INSTALL_PATH}}/{{.BINARY_NAME}}
      - echo "✅ Installation complete"

  uninstall:
    desc: Remove goman from system path
    cmds:
      - echo "🗑️  Removing {{.BINARY_NAME}} from {{.INSTALL_PATH}}..."
      - sudo rm -f {{.INSTALL_PATH}}/{{.BINARY_NAME}}
      - echo "✅ Uninstallation complete"

  # Lambda deployment
  deploy:lambda:
    desc: Deploy Lambda function to AWS
    deps: [build:lambda]
    cmds:
      - echo "🚀 Deploying Lambda function..."
      - |
        # Get AWS account ID
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        FUNCTION_NAME="goman-controller-${ACCOUNT_ID}"
        
        # Check if function exists
        if aws lambda get-function --function-name ${FUNCTION_NAME} --region {{.AWS_REGION}} > /dev/null 2>&1; then
          echo "📦 Updating Lambda function ${FUNCTION_NAME}..."
          aws lambda update-function-code \
            --function-name ${FUNCTION_NAME} \
            --zip-file fileb://{{.BUILD_DIR}}/lambda-aws-controller.zip \
            --region {{.AWS_REGION}} > /dev/null
          echo "✅ Lambda deployment complete"
        else
          echo "❌ Lambda function '${FUNCTION_NAME}' does not exist."
          echo "💡 Run 'goman init' first to initialize infrastructure."
          exit 1
        fi

  logs:lambda:
    desc: View Lambda function logs
    cmds:
      - echo "📋 Viewing Lambda logs..."
      - |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        FUNCTION_NAME="goman-controller-${ACCOUNT_ID}"
        aws logs tail /aws/lambda/${FUNCTION_NAME} --follow --region {{.AWS_REGION}}

  # Code quality tasks
  test:
    desc: Run tests
    cmds:
      - echo "🧪 Running tests..."
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - echo "🧪 Running tests with coverage..."
      - go test -v -cover ./...

  fmt:
    desc: Format code
    cmds:
      - echo "🎨 Formatting code..."
      - go fmt ./...
      - echo "✅ Code formatted"

  lint:
    desc: Run linter
    cmds:
      - echo "🔍 Running linter..."
      - |
        if command -v golangci-lint &> /dev/null; then
          golangci-lint run
        else
          echo "❌ golangci-lint not installed. Install with:"
          echo "  brew install golangci-lint"
          exit 1
        fi

  check:
    desc: Run all checks (fmt, lint, test)
    cmds:
      - task: fmt
      - task: lint
      - task: test

  # Dependency management
  deps:
    desc: Download and tidy dependencies
    cmds:
      - echo "📦 Managing dependencies..."
      - go mod download
      - go mod tidy
      - echo "✅ Dependencies updated"

  deps:update:
    desc: Update all dependencies
    cmds:
      - echo "⬆️  Updating dependencies..."
      - go get -u ./...
      - go mod tidy
      - echo "✅ Dependencies updated"

  # Clean tasks
  clean:
    desc: Clean build artifacts
    cmds:
      - echo "🧹 Cleaning build artifacts..."
      - rm -f {{.BINARY_NAME}}
      - rm -rf {{.BUILD_DIR}}
      - rm -f lambda/controller/bootstrap
      - echo "✅ Clean complete"

  # Development setup
  setup:dev:
    desc: Setup development environment
    cmds:
      - echo "🛠️  Setting up development environment..."
      - go install github.com/cosmtrek/air@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - task: deps
      - echo "✅ Development environment ready"

  # Docker tasks
  docker:build:
    desc: Build Docker image
    cmds:
      - echo "🐳 Building Docker image..."
      - docker build -t goman:latest .

  docker:run:
    desc: Run in Docker
    deps: [docker:build]
    cmds:
      - docker run -it --rm -e AWS_PROFILE -e AWS_REGION -v ~/.aws:/root/.aws:ro goman:latest

  # Release tasks
  release:
    desc: Build release binaries for all platforms
    cmds:
      - echo "📦 Building release binaries..."
      - mkdir -p dist
      # macOS
      - GOOS=darwin GOARCH=amd64 go build -o dist/{{.BINARY_NAME}}-darwin-amd64 ./cmd/goman
      - GOOS=darwin GOARCH=arm64 go build -o dist/{{.BINARY_NAME}}-darwin-arm64 ./cmd/goman
      # Linux
      - GOOS=linux GOARCH=amd64 go build -o dist/{{.BINARY_NAME}}-linux-amd64 ./cmd/goman
      - GOOS=linux GOARCH=arm64 go build -o dist/{{.BINARY_NAME}}-linux-arm64 ./cmd/goman
      # Windows
      - GOOS=windows GOARCH=amd64 go build -o dist/{{.BINARY_NAME}}-windows-amd64.exe ./cmd/goman
      - echo "✅ Release binaries built in dist/"

  # Testing tasks
  test:e2e:
    desc: Run end-to-end tests
    cmds:
      - echo "🧪 Running end-to-end tests..."
      - ./scripts/e2e_test.sh

  test:quick:
    desc: Run quick tests
    cmds:
      - echo "🧪 Running quick tests..."
      - ./scripts/quick_test.sh

  check:resources:
    desc: Check AWS resources across regions
    cmds:
      - echo "🔍 Checking AWS resources..."
      - ./scripts/check_resources.sh

  # Watch for changes (requires fswatch)
  watch:
    desc: Watch for changes and rebuild
    cmds:
      - |
        echo "👀 Watching for changes..."
        if command -v fswatch &> /dev/null; then
          fswatch -o pkg cmd | xargs -n1 -I{} task build:ui
        else
          echo "❌ fswatch not installed. Install with:"
          echo "  brew install fswatch"
          exit 1
        fi